# Generated by Django 3.1.2 on 2020-10-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20201027_0800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='average',
        ),
        migrations.AddField(
            model_name='rate',
            name='creativityaverage',
            field=models.FloatField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='designaverage',
            field=models.FloatField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='total',
            field=models.FloatField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='usabilityaverage',
            field=models.FloatField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='rate',
            name='creativity',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='rate',
            name='design',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rate',
            name='usability',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
