# Generated by Django 3.1.2 on 2020-10-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20201027_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='content',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rate',
            name='design',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rate',
            name='total',
            field=models.FloatField(blank=True, default=0, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='rate',
            name='usability',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
